services:
  picopark-server:
    build:
      context: .
      dockerfile: servidor/Dockerfile
    container_name: picopark-server
    ports:
      - "8081:3000"        
    environment:
      - HOST_PUBLICO=10.56.31.30    
      - PUERTO_PUBLICO=8081        
    restart: unless-stopped